### ISSUE TITLE
Potential security vulnerabilities in dependencies

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/ArachneCommons#148]
- https://github.com/OHDSI/ArachneCommons/network/alert/arachne-commons/pom.xml/org.apache.tika:tika-core/open 
- https://github.com/OHDSI/ArachneCommons/network/alert/execution-engine-commons/pom.xml/org.springframework:spring-core/open
- https://github.com/OHDSI/ArachneCommons/network/alert/logging/pom.xml/org.springframework:spring-core/open
- https://github.com/OHDSI/ArachneCommons/network/alert/arachne-commons/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

**Comment by acumarav** [comment]
Mentioned alerts have been fixed
