### ISSUE TITLE
Unable to build ArachneCommons

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/ArachneCommons#225]
Tracing through dependencies related to https://github.com/OHDSI/Atlas/pull/2064, we've discovered that we're currently unable to build this project. Here is the output while attempting to clean & build `arachne-commons-bundle`:

````
arachne-commons-bundle ............................ SUCCESS [0.815s]
arachne-common-types .............................. SUCCESS [5.317s]
arachne-commons ................................... SUCCESS [14.216s]
arachne-sys-settings .............................. FAILURE [2.463s]
execution-engine-commons .......................... SKIPPED
arachne-storage ................................... SKIPPED
arachne-no-handler-found-exception-util ........... SKIPPED
logging ........................................... SKIPPED
arachne-common-utils .............................. SKIPPED
data-source-manager ............................... SKIPPED
arachne-scheduler ................................. SKIPPED
````

Building `arachne-sys-settings` alone reveals the issue related to https://github.com/OHDSI/WebAPI/issues/1432:

````
Failed to execute goal on project arachne-sys-settings:

Could not resolve dependencies for project com.odysseusinc.arachne:arachne-sys-settings:jar:1.16.0-SNAPSHOT: 
Failed to collect dependencies for [
org.postgresql:postgresql:jar:42.2.1 (compile), 
com.odysseusinc.arachne:arachne-commons:jar:1.16.0-SNAPSHOT (compile), 
io.springfox:springfox-swagger2:jar:2.9.2 (compile), 
org.springframework.boot:spring-boot-starter-web:jar:1.5.22.RELEASE (compile), 
org.springframework.boot:spring-boot-starter-security:jar:1.5.22.RELEASE (compile), 
org.springframework.cloud:spring-cloud-context:jar:1.2.0.RELEASE (compile), 
org.springframework.boot:spring-boot-starter-data-jpa:jar:1.5.22.RELEASE (compile), 
org.springframework.boot:spring-boot-starter-actuator:jar:1.5.22.RELEASE (compile), 
org.flywaydb:flyway-core:jar:4.2.0 (compile), 
com.github.ulisesbocchio:jasypt-spring-boot-starter:jar:1.18 (compile)]: 

Failed to read artifact descriptor for org.springframework.boot:spring-boot-starter-web:jar:1.5.22.RELEASE: 
Could not transfer artifact org.springframework.boot:spring-boot-starter-web:pom:1.5.22.RELEASE from/to central (http://repo.maven.apache.org/maven2): 
Failed to transfer file: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-web/1.5.22.RELEASE/spring-boot-starter-web-1.5.22.RELEASE.pom. 

Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
````

Tagging @wivern and @olga-ganina for awareness.

**Comment by YaroslavTir** [comment]
**Reason** 
The reason for the observed error is explained in Central 501 HTTPS Required
https://stackoverflow.com/a/59764670/1167673

> Effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.

It looks like the latest versions of Maven (since version 3.2.3) is already using the HTTPS URL by default.
http://maven.apache.org/docs/3.2.3/release-notes.html

so most likely you have the wrong configuration for the central repository in your `./m2/setting.xml` file
```
                <repository>
                    <id>central</id>
                    <name>Central Repository</name>
                    ...
                <repository>
```
**Fix**
1) check maven version `mvn -version` , it should be >3.2.3. If it is not, then upgrade maven.
2) remove the central repository from setting.xml. This repository is properly configured by default.

**Comment by YaroslavTir** [comment]
If for some reason the version of the maven is lower than 3.2.3 and it is impossible to upgrade it(but this is an antique version of 2014 and it is strongly recommended to upgrade), then just change the central repository to:
```
                <repository>
                    <id>central</id>
                    <name>Central Repository</name>
                    <url>https://repo.maven.apache.org/maven2</url>
                    ...
                </repository>
```

**Comment by anthonysena** [comment]
@YaroslavTir - my Maven version is 3.6.0 and I do not have a reference to the Central Repository in my settings.xml. So I'm unsure why it is failing.

Here is my current thinking: the `distributionManagement` configuration in this repo uses `repo.odysseusinc.com` and it appears that `com.github.ulisesbocchio:jasypt-spring-boot-starter:jar:1.18` does not exist on the nexus repo. My guess is that when the `repo.odysseusinc.com` cannot resolve a reference, it is forwarding to `http://repo.maven.apache.org/maven2` to try and resolve the dependency. What do you think of this theory?

**Comment by YaroslavTir** [comment]
Hi @anthonysena 
That is an interesting guess, but I checked this, and it looks like it is everything right with nexus(we are use artifactory, but it is pretty much the same):
1) artifactory has a link only to the `https://jcenter.bintray.com`.  (JCenter is a superset of Maven Central, served by Bintray. It contains everything in Maven Central)
2) I was able to find `jasypt-spring-boot` dependency in the artifactory using web-interface
3) As I can see there is no explicit  forwarding behind the hood for community-libs-snapshot-local and community-libs-release-local
Another thing is that it is not so easy to disable to the central repository https://stackoverflow.com/a/49113849/1167673

I have found that there is one more settings.xml file. This is a default file for maven.  on my linux machine it locates in the  `/etc/maven/settings.xml `
Can you check that you don't have override central repo there?

**Comment by anthonysena** [comment]
Hi @YaroslavTir - thanks for continuing to investigate things. I did some checking on this and can confirm that my settings.xml does not contain a reference to Maven Central in it. For reference, on Windows this is located in `C:\Users\<user>\.m2\settings.xml` or `%MAVEN_HOME%\conf\settings.xml`. I've checked both places and neither contain a reference to Maven Central. I was trying to see if there was some higher-order configuration which lead me to this: https://stackoverflow.com/a/6798517. I was able to find this at `%MAVEN_HOME%\lib\maven-model-builder-3.6.0\org\apache\maven\model\pom-4.0.0.xml` and it contains the following:

````
<project>
  <modelVersion>4.0.0</modelVersion>

  <repositories>
    <repository>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
      <layout>default</layout>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
      <layout>default</layout>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
    </pluginRepository>
  </pluginRepositories>
````

This all looks correct to me since it is using SSL. Let me also share with you the full build output for `arachne-sys-settings` for reference since it seems you can build this project while I cannot. It would be good to compare my output to your own to see what might differ:

````
------------------------------------------------------------------------
Building arachne-sys-settings 1.16.0-SNAPSHOT
------------------------------------------------------------------------
Downloading: http://repo.odysseusinc.com/artifactory/community-libs-release-local/org/springframework/boot/spring-boot-starter-web/1.5.22.RELEASE/spring-boot-starter-web-1.5.22.RELEASE.pom

Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-web/1.5.22.RELEASE/spring-boot-starter-web-1.5.22.RELEASE.pom

Downloading: http://repo.odysseusinc.com/artifactory/community-libs-release-local/org/springframework/boot/spring-boot-starter-security/1.5.22.RELEASE/spring-boot-starter-security-1.5.22.RELEASE.pom

Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-security/1.5.22.RELEASE/spring-boot-starter-security-1.5.22.RELEASE.pom

Downloading: http://repo.odysseusinc.com/artifactory/community-libs-release-local/org/springframework/boot/spring-boot-starter-data-jpa/1.5.22.RELEASE/spring-boot-starter-data-jpa-1.5.22.RELEASE.pom

Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-data-jpa/1.5.22.RELEASE/spring-boot-starter-data-jpa-1.5.22.RELEASE.pom

Downloading: http://repo.odysseusinc.com/artifactory/community-libs-release-local/org/springframework/boot/spring-boot-starter-actuator/1.5.22.RELEASE/spring-boot-starter-actuator-1.5.22.RELEASE.pom

Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-actuator/1.5.22.RELEASE/spring-boot-starter-actuator-1.5.22.RELEASE.pom

Downloading: http://repo.odysseusinc.com/artifactory/community-libs-release-local/com/github/ulisesbocchio/jasypt-spring-boot-starter/1.18/jasypt-spring-boot-starter-1.18.pom

Downloading: http://repo.maven.apache.org/maven2/com/github/ulisesbocchio/jasypt-spring-boot-starter/1.18/jasypt-spring-boot-starter-1.18.pom

------------------------------------------------------------------------
Reactor Summary:

arachne-commons-bundle ............................ SUCCESS [1.866s]
arachne-common-types .............................. SUCCESS [5.568s]
arachne-commons ................................... SUCCESS [13.405s]
arachne-sys-settings .............................. FAILURE [2.823s]
execution-engine-commons .......................... SKIPPED
arachne-storage ................................... SKIPPED
arachne-no-handler-found-exception-util ........... SKIPPED
logging ........................................... SKIPPED
arachne-common-utils .............................. SKIPPED
data-source-manager ............................... SKIPPED
arachne-scheduler ................................. SKIPPED
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 24.208s
Finished at: Thu Jan 30 08:33:12 EST 2020
Final Memory: 36M/343M
------------------------------------------------------------------------
Failed to execute goal on project arachne-sys-settings: Could not resolve dependencies for project com.odysseusinc.arachne:arachne-sys-settings:jar:1.16.0-SNAPSHOT: Failed to collect dependencies for [org.postgresql:postgresql:jar:42.2.1 (compile), com.odysseusinc.arachne:arachne-commons:jar:1.16.0-SNAPSHOT (compile), io.springfox:springfox-swagger2:jar:2.9.2 (compile), org.springframework.boot:spring-boot-starter-web:jar:1.5.22.RELEASE (compile), org.springframework.boot:spring-boot-starter-security:jar:1.5.22.RELEASE (compile), org.springframework.cloud:spring-cloud-context:jar:1.2.0.RELEASE (compile), org.springframework.boot:spring-boot-starter-data-jpa:jar:1.5.22.RELEASE (compile), org.springframework.boot:spring-boot-starter-actuator:jar:1.5.22.RELEASE (compile), org.flywaydb:flyway-core:jar:4.2.0 (compile), com.github.ulisesbocchio:jasypt-spring-boot-starter:jar:1.18 (compile)]: Failed to read artifact descriptor for org.springframework.boot:spring-boot-starter-web:jar:1.5.22.RELEASE: Could not transfer artifact org.springframework.boot:spring-boot-starter-web:pom:1.5.22.RELEASE from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-web/1.5.22.RELEASE/spring-boot-starter-web-1.5.22.RELEASE.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

After correcting the problems, you can resume the build with the command
  mvn <goals> -rf :arachne-sys-settings
````

As you can see above, there are duplicate download attempts - let's take the 1st:

````
Downloading: http://repo.odysseusinc.com/artifactory/community-libs-release-local/org/springframework/boot/spring-boot-starter-web/1.5.22.RELEASE/spring-boot-starter-web-1.5.22.RELEASE.pom

Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-web/1.5.22.RELEASE/spring-boot-starter-web-1.5.22.RELEASE.pom
````

If I navigate to: http://repo.odysseusinc.com/artifactory/community-libs-release-local/org/, I do not see any reference to `springframework`:

![image](https://user-images.githubusercontent.com/12902366/73455605-67feb300-433e-11ea-88d2-3b5374580783.png)

That's where I suspected that some configuration (either on the Nexus repo, the project itself or my own local Maven configuration) is then attempting to retrieve the reference from Maven Central. So, as a test, I just revised the pom.xml in the `arachne-commons-bundle` to explicitly define the Maven Central location as shown here:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>arachne-commons-bundle</artifactId>
    <groupId>com.odysseusinc.arachne</groupId>
    <version>1.16.0-SNAPSHOT</version>
    <packaging>pom</packaging>

  <repositories>
    <repository>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2/ </url>
    </repository>
  </repositories>

..... [omitted]
```

Once that was done, I was able to compile without issue. Sorry for sharing so many details but thought it was important in case others run into something similar.

**Comment by YaroslavTir** [comment]
@anthonysena that is interesting, I am now really curious. 
> Sorry for sharing so many details but I thought it was important in case others run into something similar.

That's totally right. 

The thing is that I even cannot reproduce this behaver(unless I explicitly define the http Maven Central in pom,xml or settings.xml).

I created a really simple maven application https://github.com/YaroslavTir/maven-http-issue
Can you try to run this one? with setting.xml and without(you can rename .m2/settings.xml for this experiment), so we can understand where the issue is lieing.  project, nexus or your environment issue. 
I also revise all our projects and have found some using http central, but arachne-common is not among them.

https://github.com/search?q=org%3AOHDSI+repo.maven.apache.org%2Fmaven2&type=Code

**Comment by anthonysena** [comment]
Thanks for doing that @YaroslavTir - I think the problem lies in my NetBeans IDE somewhere. I was able to compile this simple project directly from the maven command line without issue. I need to dig into what is happening in my IDE but likely it needs an upgrade to a newer version of Maven.

**Comment by YaroslavTir** [comment]
@anthonysena super, any way you have found an issue that affect our other projects,  well done :)

**Comment by anthonysena** [comment]
Running NetBeans 8.2 which by default was using Maven 3.0.5 as shown below:

![image](https://user-images.githubusercontent.com/12902366/73473477-db162280-435a-11ea-977f-6fa125d709b8.png)

I changed this to use 3.6.0 which I have locally as well:

![image](https://user-images.githubusercontent.com/12902366/73473630-13b5fc00-435b-11ea-978c-b54fbb5e9850.png)

That fixed the issue. The question remains: does it do us any harm to make sure that we're explicitly requiring the SSL endpoint as part of the pom.xml in this project and the others?

**Comment by YaroslavTir** [comment]
we do not need explicit dependency in our poms. From my point of view, this just creates one more possibility for error in the future. I would rely on the maven default setting to resolve central repo

**Comment by anthonysena** [comment]
@YaroslavTir - thanks for the good discussion around this topic. I agree with you in principle: we should not explicitly require things that are set by default by the underlying component. However, in this case the change that was that Maven Central Repo dropped support of HTTP. What is not obvious: if you are running an older version of Maven (as I was by default via NetBeans) it is not obvious _why_ the build will fail.

So, I'm going to ask that we include the explicit reference to Maven as was done here: https://github.com/OHDSI/ArachneCommons/pull/226/commits/8693e553c88bf24b4c55503474b06232d57dbfec. In this way, if a person is running an older version of Maven, the would still be able to download the components via SSL and things would work.

In addition, I think we should consider enforcing some minimally supported version of Maven so that we can be sure that people using these Java components know that they should be using a newer version of Maven to compile the work. To that end, I've added this commit: https://github.com/OHDSI/ArachneCommons/pull/226/commits/adb396dcdd5174e2e3a08883a75f05226e6b7e60 which takes advantage of the Maven enforcer to make sure that people are using 3.6.0. More info on that plugin here: https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html.

**Note**: I picked 3.6.0 arbitrarily - it is what I currently have on my system. Perhaps we can identify which version of maven started to support SSL by default and use that instead?

**Comment by anthonysena** [comment]
FYI - if we don't explictly define the SSL connection as I described above then the Enforcer plugin will not download (since it will be requested over HTTP) so that's another reason why we should consider these in tandem.

Also, thanks for contributing fixes for this issue to the other repositories but I'd suggest that we get this issue resolved here and once we have a fix that is agreeable, we then push that out to the the repos.

**Comment by YaroslavTir** [comment]
I am on the fence, I hear what you say, and this is right we should avoid any possibilities of error, and should be proactive here.
On the other hand, http/https stuff was fixed in 3.2.3 version and it was **2014-08-17 more than 5 years ago**!! (the funny thing is that maven was written on the java6 ).  NetBeans version 8.2 itself was released on October 3, 2016, that also a really old version(if I am not wrong NetBeans moved from oracle to apache after 8.2 and now it is Apache NetBeans, so I recommend you to upload the last version :)). I personally think that set implicit versions and explicit reference to pom.xml is overkill. I can agree to change our readme notes. Add the minimal maven support version and probably we can describe how to set central repository in settings.xml file for oldest versions.

**Comment by anthonysena** [comment]
> I can agree to change our readme notes. Add the minimal maven support version and probably we can describe how to set central repository in settings.xml file for oldest versions.

Can you update https://github.com/OHDSI/ArachneCommons/pull/226 to reflect what you'd like to see happen here? I can then review and we can hopefully decide how we'd like to make this work for the other repositories. I'm a bit torn on the best way to handle this since I currently think that the errors produced by old version of Maven against components that do not explicitly state the SSL location for the Central repo are not helpful to debug the actual issue (that Maven is super old).

**Comment by anthonysena** [comment]
After some more thinking, I think leaving the pom.xml in this project the way it is makes good sense. We've now documented that there are issues when using very, very old versions of Maven. If we find that we're running into this problem elsewhere in the OHDSI community then we can revisit this decision and see if we'd like to adopt some of the options reviewed here. Thanks!
